export const API_URLS = {
    AUTHENTICATE: 'authenticate/token',
    GOOGLE_AUTHENTICATE: 'authenticate/google',
    FORGOT_PASSWORD: 'authenticate/forgot-password',
    VERIFY_OTP: 'authenticate/verify-otp',
    RESET_PASSWORD: 'authenticate/reset-password',
    SET_PASSWORD: 'authenticate/set-password',
    LOGOUT: 'authenticate/logout',
    FETCH_PROFILE: 'profile',
    UPDATE_PROFILE: 'profile',
    REQUEST_CHANGE_PASSWORD_OTP: 'profile/change-password/request-otp',
    VERIFY_CHANGE_PASSWORD_OTP: 'profile/change-password/verify-otp',
    CHANGE_PASSWORD: 'profile/change-password',
    CREATE_REGISTER_USER: 'user/signup',
    VERIFY_SIGNUP_OTP: 'user/verify-signup-otp',
    RESEND_SIGNUP_OTP: 'user/resend-signup-otp',
    FIND_USER_BY_ID: 'user/:id',
    UPDATE_USER: 'user',

    FILTER_USER: 'user/filter',
    CREATE_USER: 'user',
    REMOVE_USER: 'user/:id',

    FILTER_ROLE: 'role/filter',
    CREATE_ROLE: 'role',
    UPDATE_ROLE: 'role',
    FIND_ROLE_BY_ID: 'role/:id',
    REMOVE_ROLE: 'role/:id',

    FILTER_PERMISSION: 'permission/filter',
    CREATE_PERMISSION: 'permission',
    UPDATE_PERMISSION: 'permission',
    FIND_PERMISSION_BY_ID: 'permission/:id',
    REMOVE_PERMISSION: 'permission/:id',

    FILTER_USER_GROUP: 'user-group/filter',
    CREATE_USER_GROUP: 'user-group',
    UPDATE_USER_GROUP: 'user-group',
    FIND_USER_GROUP_BY_ID: 'user-group/:id',
    REMOVE_USER_GROUP: 'user-group/:id',

    FILTER_SYSTEM_CONFIG: 'system-config/filter',
    UPDATE_SYSTEM_CONFIG: 'system-config',
    FIND_SYSTEM_CONFIG_BY_ID: 'system-config/:id',
    FIND_SYSTEM_CONFIG_BY_KEY: 'system-config/key/:configKey',

    FIND_PASSWORD_POLICY: 'password-policy',
    UPDATE_PASSWORD_POLICY: 'password-policy',

    FILTER_EXCEPTION_LOG: 'exception-log/filter',
    FIND_EXCEPTION_LOG_BY_ID: 'exception-log/:id',
    REMOVE_EXCEPTION_LOG: 'exception-log/:id',

    FILTER_SESSION: 'session/filter',
    FIND_SESSION_BY_ID: 'session/:id',
    SESSION_SUMMARY: 'session/summary',
    SESSIONS_BY_USER: 'session/user/:userId',
    REMOVE_SESSION: 'session/:id',
    FORCE_LOGOUT_ALL: 'session/all',

    FILTER_AUDIT_LOG: 'audit-log/filter',
    FIND_AUDIT_LOG_BY_ID: 'audit-log/:id',

    FILTER_ARCHIVE_CONFIG: 'archive-config/filter',
    CREATE_ARCHIVE_CONFIG: 'archive-config',
    UPDATE_ARCHIVE_CONFIG: 'archive-config',
    FIND_ARCHIVE_CONFIG_BY_ID: 'archive-config/:id',
    REMOVE_ARCHIVE_CONFIG: 'archive-config/:id',
    LIST_ARCHIVE_CONFIG_SOURCE_TABLES: 'archive-config/source-tables',
    LIST_ARCHIVE_CONFIG_SCHEMAS: 'archive-config/schemas',
    LIST_ARCHIVE_CONFIG_DATE_COLUMNS: 'archive-config/date-columns',
    LIST_ARCHIVE_CONFIG_COLUMNS: 'archive-config/columns',
    ARCHIVE_CONFIG_ARCHIVE_NOW: 'archive-config/:id/archive-now',
    FIND_ARCHIVE_CONFIG_ARCHIVED_DATA: 'archive-config/:id/archived-data',

    FILTER_COMPANY: 'company/filter',
    CREATE_COMPANY: 'company',
    UPDATE_COMPANY: 'company',
    FIND_COMPANY_BY_ID: 'company/:id',
    REMOVE_COMPANY: 'company/:id',

    FILTER_COMPANY_TYPE: 'company-type/filter',
    CREATE_COMPANY_TYPE: 'company-type',

    FILTER_JOB_POSTING: 'job-circular/filter',
    CREATE_JOB_POSTING: 'job-circular',
    UPDATE_JOB_POSTING: 'job-circular',
    FIND_JOB_POSTING_BY_ID: 'job-circular/:id',
    REMOVE_JOB_POSTING: 'job-circular/:id',
    AI_SUGGEST_JOB_POSTING: 'job-circular/ai-suggest',

    FETCH_CANDIDATE_PROFILE: 'candidate-profile',
    UPDATE_CANDIDATE_PROFILE: 'candidate-profile',
    GENERATE_CANDIDATE_CV: 'candidate-profile/generate-cv',
    LIST_CANDIDATE_CVS: 'candidate-profile/cv',
    DOWNLOAD_CANDIDATE_CV: 'candidate-profile/cv/:id/download',

    APPLY_TO_JOB: 'application',
    MY_APPLICATIONS: 'application/my',
    FILTER_APPLICATIONS: 'application/filter',
    FIND_APPLICATION_BY_ID: 'application/:id',
    CHANGE_APPLICATION_STATUS: 'application/:id/status',
    APPLICATION_HISTORY: 'application/:id/history',
    DOWNLOAD_APPLICATION_CV: 'application/:id/cv',

    SCHEDULE_INTERVIEW: 'interview',
    FILTER_INTERVIEWS: 'interview/filter',
    FIND_INTERVIEW_BY_ID: 'interview/:id',
    INTERVIEWS_BY_APPLICATION: 'interview/by-application/:applicationId',
    CHANGE_INTERVIEW_STATUS: 'interview/:id/status',
    SUBMIT_INTERVIEW_FEEDBACK: 'interview/:id/feedback',

    CREATE_OFFER: 'offer',
    GENERATE_OFFER_LETTER: 'offer/:id/generate-letter',
    SEND_OFFER: 'offer/:id/send',
    FIND_OFFER_BY_ID: 'offer/:id',
    OFFERS_BY_APPLICATION: 'offer/by-application/:applicationId',
    MY_OFFERS: 'offer/my',
    RESPOND_TO_OFFER: 'offer/:id/respond',
    DOWNLOAD_OFFER_LETTER: 'offer/:id/letter',

    ADD_ONBOARDING_TASK: 'onboarding-task',
    ONBOARDING_TASKS_BY_APPLICATION: 'onboarding-task/by-application/:applicationId',
    COMPLETE_ONBOARDING_TASK: 'onboarding-task/:id/complete',
    REMOVE_ONBOARDING_TASK: 'onboarding-task/:id',

    TOGGLE_SAVED_JOB: 'saved-job/toggle/:jobCircularId',
    MY_SAVED_JOBS: 'saved-job/my',

    SAVE_JOB_ALERT: 'job-alert',
    MY_JOB_ALERTS: 'job-alert/my',
    REMOVE_JOB_ALERT: 'job-alert/:id',

    ANALYTICS_SUMMARY: 'analytics/summary',
    ANALYTICS_FUNNEL: 'analytics/funnel',

    SUBMIT_RECRUITER_APPLICATION: 'recruiter-application',
    FILTER_RECRUITER_APPLICATION: 'recruiter-application/filter',
    FIND_RECRUITER_APPLICATION_BY_ID: 'recruiter-application/:id',
    APPROVE_RECRUITER_APPLICATION: 'recruiter-application/:id/approve',
    REJECT_RECRUITER_APPLICATION: 'recruiter-application/:id/reject',

};